title: Duy Phuong Nguyen (Buzi)
subtitle: PhD Student, Electrical and Computer Engineering
author:
  name: Duy Phuong Nguyen
  email-acad: duyn@princeton.edu
  email-other: buzinguyen@gmail.com
  phone: (609) 375 6109
  avatar: "/assets/img/avatar.jpeg"
  bio: "Robotics Researcher, Maker and Enthusiast"
  location: "Princeton, New Jersey, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/buzi-princeton"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=BpR72EcAAAAJ"
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/buzinguyen"

description: > # this means to ignore newlines until "show_excerpts:"
  Robotics Researcher, Maker and Enthusiast

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
# minima:
#   date_format: "%b %-d, %Y"

#   # generate social links in footer
#   social_links:
#     - { platform: github,         user_url: "https://github.com/buzi-princeton" }
#     - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=BpR72EcAAAAJ" }
#     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/buzinguyen" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Default configs
defaults:
  - scope:
      path: ""
    values:
      author_profile: true

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
github:
  - repository: buzinguyen/buzinguyen.github.io

plugins:
  - jekyll-seo-tag
  # - jekyll/scholar
  - jekyll-include-cache

# Mmistakes configs
breadcrumbs: true